#!/usr/bin/env python3
# Copyright 2026 Anastasiia Birillo
# SPDX-License-Identifier: Apache-2.0
"""Build review statistics for SIGCSE TS 2027 (Posters) from EasyChair exports.

Input files (looked up in input/ by default, the newest one wins):
  input/*review_list*.txt          - Administration -> List of reviews, all options on, Generate list
  input/SIGCSE_TS_2027_*.xlsx      - Submissions in Excel, no checkboxes selected, Download
  input/assignment/assignment.csv  - Assignment -> Download in CSV (reviewer id, paper number)
  input/assignment/reviewer.csv    - same archive (id, name, email, role)

Output: output/review_stats_<date>.xlsx - import it into Google Sheets
via File -> Import -> Upload -> "Replace spreadsheet".
"""

import argparse
import csv
import re
import sys
import zipfile
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from datetime import datetime
from itertools import zip_longest
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

BASE = Path(__file__).resolve().parent
DEFAULT_INPUT = BASE / "input"
DEFAULT_OUTPUT = BASE / "output"

# Progress statuses: (sort order, label, fill color, font color)
NOT_STARTED = (0, "Not started", "F4CCCC", "000000")
UNDER_HALF = (1, "Less than half", "FFF2CC", "000000")
OVER_HALF = (2, "Half or more", "D9EAD3", "000000")
DONE = (3, "Done", "6AA84F", "FFFFFF")
STATUSES = [NOT_STARTED, UNDER_HALF, OVER_HALF, DONE]
# Only used for candidate reviewers who have nothing assigned yet
NO_ASSIGNMENTS = (4, "No assignments", "EFEFEF", "000000")

ROLE_NAMES = {"pc": "PC member", "senior": "senior PC", "chair": "track chair"}

DEFAULT_MIN_REVIEWERS = 5
DEFAULT_MAX_ASSIGNED = 7
TOP_CANDIDATES = 3
# Candidate pools on the "Needs help" tab: (key, column label, section title);
# {max} is replaced with the --max-assigned value
CANDIDATE_GROUPS = [
    ("low", "1-{max} assigned", "1-{max} assignments"),
    ("zero", "0 assigned", "no assignments yet"),
]
# Bid values from bid.csv; a higher weight ranks the candidate higher
BID_WEIGHTS = {"yes": 2, "maybe": 1, "no": -1}


def status_for(done, total):
    if done == 0:
        return NOT_STARTED
    if done >= total:
        return DONE
    if done / total < 0.5:
        return UNDER_HALF
    return OVER_HALF


# ---------- reading input data ----------

def newest(folder, pattern, exclude=None):
    files = [p for p in folder.glob(pattern) if not (exclude and exclude in p.name)]
    return max(files, key=lambda p: p.stat().st_mtime) if files else None


def read_submissions_xlsx(path):
    """EasyChair writes xlsx with invalid styles that openpyxl can't open, so read the XML directly."""
    ns = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
    tag_t = "{%s}t" % ns["m"]
    with zipfile.ZipFile(path) as z:
        strings = [
            "".join(t.text or "" for t in si.iter(tag_t))
            for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall("m:si", ns)
        ]
        sheet = ET.fromstring(z.read("xl/worksheets/sheet1.xml"))
    rows = []
    for r in sheet.iter("{%s}row" % ns["m"]):
        row = {}
        for c in r.findall("m:c", ns):
            v = c.find("m:v", ns)
            val = v.text if v is not None else ""
            if c.get("t") == "s":
                val = strings[int(val)]
            row[re.match(r"[A-Z]+", c.get("r")).group()] = " ".join(val.split())
        rows.append(row)
    header = rows[0]
    col = {name: key for key, name in header.items()}
    subs = {}
    for row in rows[1:]:
        num = row.get(col["#"], "")
        if num:
            subs[num] = {"title": row.get(col["Title"], ""), "authors": row.get(col["Authors"], "")}
    return subs


def parse_reviews(path):
    text = Path(path).read_text(encoding="utf-8")
    m = re.search(r"generated by EasyChair for .+? on (\d{4}-\d{2}-\d{2})", text)
    export_date = m.group(1) if m else ""

    papers = {}
    reviews = []
    parts = re.split(r"\*{5,} PAPER (\d+) \*{5,}", text)
    for num, body in zip(parts[1::2], parts[2::2]):
        title = re.search(r"^TITLE: (.*)$", body, re.M)
        authors = re.search(r"^AUTHORS: (.*)$", body, re.M)
        decision = re.search(r"^PRELIMINARY DECISION: (.*)$", body, re.M)
        papers[num] = {
            "title": title.group(1).strip() if title else "",
            "authors": authors.group(1).strip() if authors else "",
            "decision": decision.group(1).strip() if decision else "",
        }
        blocks = re.split(r"^\+{5,} REVIEW (\d+) \((.+?)\) \+{5,}$", body, flags=re.M)
        for idx, name, rbody in zip(blocks[1::3], blocks[2::3], blocks[3::3]):
            header, _, rest = rbody.partition("\n---- ")
            fields = {}
            for line in header.strip().splitlines():
                if ": " in line:
                    k, v = line.split(": ", 1)
                    fields[k.strip()] = v.strip()
            sections = {}
            for sec in re.split(r"^---- ", "---- " + rest, flags=re.M)[1:]:
                sec_name, _, sec_text = sec.partition(" ----\n")
                sections[sec_name.strip()] = sec_text.strip()
            score = fields.pop("TOTAL SCORE", "")
            fam = fields.pop("Familiarity", "")
            fam_num = re.match(r"\d+", fam)
            reviews.append({
                "paper": num,
                "review_no": int(idx),
                "reviewer": name.strip(),
                "score": int(score) if re.fullmatch(r"-?\d+", score) else score,
                "familiarity": int(fam_num.group()) if fam_num else None,
                "familiarity_text": fam,
                "extra": fields,
                "sections": sections,
            })
    return export_date, papers, reviews


def read_pc(folder):
    reviewers = {}
    with open(folder / "reviewer.csv", encoding="utf-8") as f:
        for row in csv.reader(f):
            if len(row) >= 4:
                rid, name, email, role = row[:4]
                reviewers[rid] = {"name": name, "email": email, "role": ROLE_NAMES.get(role, role)}
    assignments = []
    with open(folder / "assignment.csv", encoding="utf-8") as f:
        for row in csv.reader(f):
            if len(row) >= 2:
                assignments.append((row[0], row[1]))
    return reviewers, assignments


def read_optional_csv(path):
    if not path.exists():
        return []
    with open(path, encoding="utf-8") as f:
        return [row for row in csv.reader(f) if row]


def read_matching(folder):
    """Conflicts, bids and topics from the same Assignment -> Download in CSV archive."""
    conflicts = {(r[0], r[1]) for r in read_optional_csv(folder / "conflict.csv") if len(r) >= 2}
    bids = {}
    for r in read_optional_csv(folder / "bid.csv"):
        if len(r) >= 3:
            bid = r[2].strip().lower()
            if bid == "conflict":
                conflicts.add((r[0], r[1]))
            else:
                bids[(r[0], r[1])] = bid
    rev_topics, sub_topics = defaultdict(set), defaultdict(set)
    for r in read_optional_csv(folder / "reviewer_topic.csv"):
        if len(r) >= 2:
            rev_topics[r[0]].add(r[1])
    for r in read_optional_csv(folder / "submission_topic.csv"):
        if len(r) >= 2:
            sub_topics[r[0]].add(r[1])
    return conflicts, bids, rev_topics, sub_topics


# ---------- formatting ----------

HEADER_FILL = PatternFill("solid", fgColor="434343")
HEADER_FONT = Font(bold=True, color="FFFFFF")
WRAP_TOP = Alignment(wrap_text=True, vertical="top")


def write_table(ws, headers, rows, widths=None, status_col=None, pct_cols=(), title=None):
    """Append a table to the sheet.

    Without a title the table fills the whole sheet (frozen header and filter);
    with a title it is appended as a section below the existing content.
    """
    if title:
        if ws.max_row > 1:
            ws.append([])
        ws.append([title])
        ws.cell(ws.max_row, 1).font = Font(bold=True, size=12)
    ws.append(headers)
    for c in ws[ws.max_row]:
        c.fill, c.font, c.alignment = HEADER_FILL, HEADER_FONT, Alignment(wrap_text=True, vertical="center")
    for row in rows:
        status = row[status_col] if status_col is not None else None
        ws.append(row[:status_col] + row[status_col + 1:] if status_col is not None else row)
        r = ws.max_row
        for c in ws[r]:
            c.alignment = WRAP_TOP
            if status:
                c.fill = PatternFill("solid", fgColor=status[2])
                c.font = Font(color=status[3])
        for pc in pct_cols:
            ws.cell(r, pc).number_format = "0%"
    if widths:
        set_widths(ws, widths)
    if not title:
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = ws.dimensions


def set_widths(ws, widths):
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w


def fmt_list(values):
    return ", ".join(str(v) for v in values)


def avg(values):
    nums = [v for v in values if isinstance(v, (int, float))]
    return round(sum(nums) / len(nums), 2) if nums else ""


# ---------- main logic ----------

def build(reviews_txt, subs_xlsx, pc_folder, out_path,
          min_reviewers=DEFAULT_MIN_REVIEWERS, max_assigned=DEFAULT_MAX_ASSIGNED):
    export_date, txt_papers, reviews = parse_reviews(reviews_txt)
    reviewers, assignments = read_pc(pc_folder)
    conflicts, bids, rev_topics, sub_topics = read_matching(pc_folder)
    subs = read_submissions_xlsx(subs_xlsx) if subs_xlsx else {}
    for num, p in txt_papers.items():
        subs.setdefault(num, {"title": p["title"], "authors": p["authors"]})
    for _, num in assignments:
        subs.setdefault(num, {"title": "", "authors": ""})

    def norm(name):
        return " ".join(name.split()).casefold()

    name_to_id = {norm(r["name"]): rid for rid, r in reviewers.items()}
    assigned_by_paper = defaultdict(list)   # paper -> [reviewer id]
    assigned_by_rev = defaultdict(list)     # reviewer id -> [paper]
    for rid, num in assignments:
        assigned_by_paper[num].append(rid)
        assigned_by_rev[rid].append(num)

    warnings = []
    done_pairs = set()
    reviews_by_paper = defaultdict(list)
    for rv in reviews:
        rid = name_to_id.get(norm(rv["reviewer"]))
        rv["rid"] = rid
        rv["role"] = reviewers[rid]["role"] if rid else "?"
        if rid is None:
            warnings.append(f"Reviewer \"{rv['reviewer']}\" (paper {rv['paper']}) not found in reviewer.csv")
        elif rv["paper"] not in assigned_by_rev[rid]:
            warnings.append(f"Review by {rv['reviewer']} on paper {rv['paper']} is not in assignment.csv; counted as an extra assignment")
            assigned_by_rev[rid].append(rv["paper"])
            assigned_by_paper[rv["paper"]].append(rid)
        if rid:
            done_pairs.add((rid, rv["paper"]))
        reviews_by_paper[rv["paper"]].append(rv)

    def rname(rid):
        return reviewers.get(rid, {}).get("name", rid)

    def load(rid):
        return len(assigned_by_rev.get(rid, []))

    def paper_key(num):
        return int(num) if num.isdigit() else 0

    # --- Submissions ---
    sub_rows = []
    sub_row_by_num = {}
    for num, s in subs.items():
        assigned = assigned_by_paper.get(num, [])
        revs = sorted(reviews_by_paper.get(num, []), key=lambda r: r["review_no"])
        done_ids = {r["rid"] for r in revs}
        total = max(len(assigned), len(revs))
        st = status_for(len(revs), total) if total else NOT_STARTED
        seniors = [rid for rid in assigned if reviewers.get(rid, {}).get("role") == "senior PC"]
        senior_done = "n/a" if not seniors else ("yes" if any(r in done_ids for r in seniors) else "no")
        pending = [rname(rid) for rid in assigned if rid not in done_ids]
        row = [
            st, st[1], int(num) if num.isdigit() else num, s["title"], s["authors"],
            len(revs), total, (len(revs) / total) if total else 0, senior_done,
            fmt_list(r["score"] for r in revs), avg([r["score"] for r in revs]),
            fmt_list(r["familiarity"] for r in revs if r["familiarity"] is not None),
            avg([r["familiarity"] for r in revs]),
            fmt_list(f"{r['reviewer']} ({r['score']})" for r in revs),
            fmt_list(pending),
        ]
        sub_rows.append(row)
        sub_row_by_num[num] = row
    sub_rows.sort(key=lambda r: (r[0][0], r[7], r[2] if isinstance(r[2], int) else 0))

    # --- Reviewers (only those with assignments) ---
    def reviewer_row(rid):
        r = reviewers.get(rid, {"name": rid, "email": "", "role": "?"})
        papers = assigned_by_rev.get(rid, [])
        done = sorted(p for p in papers if (rid, p) in done_pairs)
        pending = sorted(p for p in papers if (rid, p) not in done_pairs)
        st = status_for(len(done), len(papers)) if papers else NO_ASSIGNMENTS
        return [
            st, st[1], r["name"], r["email"], r["role"], len(papers), len(done), len(pending),
            len(done) / len(papers) if papers else "", fmt_list(pending), fmt_list(done),
        ]

    rev_rows = [reviewer_row(rid) for rid in assigned_by_rev]
    rev_rows.sort(key=lambda r: (r[0][0], r[8], r[2]))

    # --- Submissions that need more reviewers and who could help ---
    short = sorted(
        (num for num in subs if len(assigned_by_paper.get(num, [])) < min_reviewers), key=paper_key
    )
    # Every paper is expected to have one senior PC; otherwise the missing reviewer is a PC member
    needed_role = {}
    for num in short:
        roles = {reviewers.get(rid, {}).get("role") for rid in assigned_by_paper.get(num, [])}
        needed_role[num] = "PC member" if "senior PC" in roles else "senior PC"

    # Two candidate pools per role: reviewers with 1..max_assigned assignments, and reviewers
    # with none. The latter are kept separate because there may be a reason they can't review.
    pools = {}  # (role, group) -> [reviewer id]
    for role in set(needed_role.values()):
        eligible = sorted((rid for rid, r in reviewers.items() if r["role"] == role), key=rname)
        pools[(role, "low")] = [rid for rid in eligible if 1 <= load(rid) <= max_assigned]
        pools[(role, "zero")] = [rid for rid in eligible if load(rid) == 0]

    # Rank candidates per paper and pool: bid first, then topic overlap, then current load
    suggestions = {}  # (paper, group) -> top candidates
    suggested_for = defaultdict(list)
    for num in short:
        for group, _, _ in CANDIDATE_GROUPS:
            ranked = []
            for rid in pools[(needed_role[num], group)]:
                if rid in assigned_by_paper.get(num, []) or (rid, num) in conflicts:
                    continue
                bid = bids.get((rid, num), "")
                overlap = sorted(rev_topics.get(rid, set()) & sub_topics.get(num, set()))
                ranked.append(((-BID_WEIGHTS.get(bid, 0), -len(overlap), load(rid), rname(rid)), rid, bid, overlap))
            ranked.sort()
            suggestions[(num, group)] = ranked[:TOP_CANDIDATES]
            for _, rid, _, _ in suggestions[(num, group)]:
                suggested_for[rid].append(num)

    def candidate_text(rid, bid, overlap):
        parts = [f"{load(rid)} assigned"]
        if bid:
            parts.append(f"bid: {bid}")
        if not rev_topics.get(rid):
            parts.append("no topics selected")
        elif overlap:
            noun = "topic" if len(overlap) == 1 else "topics"
            parts.append(f"{len(overlap)} matching {noun}: {', '.join(overlap)}")
        else:
            parts.append("0 matching topics")
        return f"{rname(rid)} ({'; '.join(parts)})"

    # --- Writing the workbook ---
    wb = Workbook()
    ws = wb.active
    ws.title = "Summary"
    total_assigned = sum(len(v) for v in assigned_by_paper.values())
    summary = [
        ("EasyChair review export", export_date),
        ("Generated at", datetime.now().strftime("%Y-%m-%d %H:%M")),
        ("", ""),
        ("Submissions", len(subs)),
        ("Reviews assigned", total_assigned),
        ("Reviews submitted", len(reviews)),
        ("Progress", len(reviews) / total_assigned if total_assigned else 0),
        (f"Submissions with < {min_reviewers} reviewers assigned", len(short)),
        ("", ""),
    ]
    for label, value in summary:
        ws.append([label, value])
    ws["B7"].number_format = "0%"
    for c in ws["A"]:
        c.font = Font(bold=True)

    def status_block(title, rows):
        ws.append([title, "Count"])
        for c in ws[ws.max_row]:
            c.fill, c.font = HEADER_FILL, HEADER_FONT
        counts = Counter(r[0] for r in rows)
        for st in STATUSES:
            ws.append([st[1], counts.get(st, 0)])
            for c in ws[ws.max_row]:
                c.fill, c.font = PatternFill("solid", fgColor=st[2]), Font(color=st[3])
        ws.append([])

    status_block("Submissions by status", sub_rows)
    status_block("Reviewers by status", rev_rows)

    ws.append(["Reviews submitted per paper", "Papers"])
    for c in ws[ws.max_row]:
        c.fill, c.font = HEADER_FILL, HEADER_FONT
    dist = Counter(r[5] for r in sub_rows)
    for k in range(0, max(dist) + 1 if dist else 1):
        ws.append([k, dist.get(k, 0)])
        ws.cell(ws.max_row, 1).alignment = Alignment(horizontal="left")

    if warnings:
        ws.append([])
        ws.append(["Warnings"])
        ws.cell(ws.max_row, 1).font = Font(bold=True, color="CC0000")
        for w in warnings:
            ws.append([w])
    ws.column_dimensions["A"].width = 34
    ws.column_dimensions["B"].width = 20

    write_table(
        wb.create_sheet("Submissions"),
        ["Status", "#", "Title", "Authors", "Submitted", "Assigned", "%", "Senior PC submitted",
         "Scores", "Avg score", "Familiarity", "Avg familiarity", "Submitted by", "Pending"],
        sub_rows,
        [18, 7, 50, 35, 8, 10, 7, 10, 12, 10, 12, 12, 40, 50],
        status_col=0, pct_cols=(7,),
    )
    write_table(
        wb.create_sheet("Reviewers"),
        ["Status", "Reviewer", "Email", "Role", "Assigned", "Submitted", "Remaining", "%",
         "Pending papers (#)", "Submitted papers (#)"],
        rev_rows,
        [18, 28, 32, 12, 10, 8, 10, 7, 40, 40],
        status_col=0, pct_cols=(8,),
    )

    ws = wb.create_sheet("Needs help")
    if not short:
        ws.append([f"All submissions have at least {min_reviewers} reviewers assigned."])
        ws.column_dimensions["A"].width = 60
    else:
        help_rows = []
        for num in short:
            base = sub_row_by_num[num]
            n_assigned = len(assigned_by_paper.get(num, []))
            cands = []
            for group, _, _ in CANDIDATE_GROUPS:
                texts = [candidate_text(rid, bid, overlap) for _, rid, bid, overlap in suggestions[(num, group)]]
                if len(texts) < TOP_CANDIDATES:
                    texts.append("no other eligible candidates" if texts else "no eligible candidates")
                    texts += [""] * (TOP_CANDIDATES - len(texts))
                cands += texts
            help_rows.append(
                base[:5] + [n_assigned, min_reviewers - n_assigned, needed_role[num]] + cands + [base[5]] + base[7:]
            )
        n_cand_cols = TOP_CANDIDATES * len(CANDIDATE_GROUPS)
        write_table(
            ws,
            ["Status", "#", "Title", "Authors", "Assigned", "Missing", "Needed role"]
            + [f"Candidate {i} ({label.format(max=max_assigned)})"
               for _, label, _ in CANDIDATE_GROUPS for i in range(1, TOP_CANDIDATES + 1)]
            + ["Submitted", "%", "Senior PC submitted", "Scores", "Avg score", "Familiarity",
               "Avg familiarity", "Submitted by", "Pending"],
            help_rows,
            status_col=0, pct_cols=(9 + n_cand_cols,),
            title=f"Submissions with fewer than {min_reviewers} reviewers assigned ({len(short)})",
        )

        for group, _, section in CANDIDATE_GROUPS:
            pool_rows = []
            desc = []
            for role in ("PC member", "senior PC"):
                pool = sorted(pools.get((role, group), []), key=lambda r: (load(r), rname(r)))
                if (role, group) in pools:
                    loads = sorted({load(rid) for rid in pool})
                    span = f" with {loads[0]}-{loads[-1]} assigned" if loads and group != "zero" else ""
                    desc.append(f"{role}: {len(pool)} people{span}")
                for rid in pool:
                    pool_rows.append(
                        reviewer_row(rid)
                        + [len(rev_topics.get(rid, ())), fmt_list(sorted(suggested_for[rid], key=paper_key))]
                    )
            write_table(
                ws,
                ["Status", "Reviewer", "Email", "Role", "Assigned", "Submitted", "Remaining", "%",
                 "Pending papers (#)", "Submitted papers (#)", "Topics selected", "Suggested for (#)"],
                pool_rows,
                status_col=0, pct_cols=(8,),
                title=f"Candidate pool: {section.format(max=max_assigned)} ({'; '.join(desc)})",
            )
        # The sections share columns, so each column gets the widest of their widths
        set_widths(ws, [max(a, b) for a, b in zip_longest(
            [18, 7, 50, 35, 10, 8, 12] + [45] * n_cand_cols + [10, 7, 10, 12, 10, 12, 12, 40, 50],
            [18, 28, 32, 12, 10, 8, 10, 7, 40, 40, 10, 20],
            fillvalue=0,
        )])

    extra_keys = sorted({k for rv in reviews for k in rv["extra"]})
    sec_keys = ["SUMMARY", "CONFIDENTIAL REMARKS FOR THE PROGRAM COMMITTEE"]
    write_table(
        wb.create_sheet("All reviews"),
        ["#", "Title", "Reviewer", "Role", "Review #", "Score", "Familiarity"] + extra_keys
        + ["Review text", "Confidential remarks for PC"],
        [
            [int(rv["paper"]), subs.get(rv["paper"], {}).get("title", ""), rv["reviewer"], rv["role"],
             rv["review_no"], rv["score"], rv["familiarity_text"]]
            + [rv["extra"].get(k, "") for k in extra_keys]
            + [rv["sections"].get(k, "")[:45000] for k in sec_keys]
            for rv in sorted(reviews, key=lambda r: (int(r["paper"]), r["review_no"]))
        ],
        [7, 40, 25, 12, 8, 8, 30] + [20] * len(extra_keys) + [80, 40],
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out_path)
    return len(subs), len(reviews), total_assigned, len(short), warnings


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("reviews_txt", nargs="?", help="TXT list of reviews (default: newest *review_list*.txt in the input dir)")
    ap.add_argument("--input-dir", default=str(DEFAULT_INPUT), help="folder with EasyChair exports (default: input/)")
    ap.add_argument("--output-dir", default=str(DEFAULT_OUTPUT), help="folder for generated xlsx (default: output/)")
    ap.add_argument("--submissions", help="xlsx list of submissions (default: newest SIGCSE_TS_2027_*.xlsx in the input dir)")
    ap.add_argument("--assignment-dir", help="folder with assignment.csv and reviewer.csv (default: <input dir>/assignment)")
    ap.add_argument("-o", "--output", help="path to the output xlsx (overrides --output-dir)")
    ap.add_argument("--min-reviewers", type=int, default=DEFAULT_MIN_REVIEWERS,
                    help=f"submissions with fewer assigned reviewers go to the 'Needs help' tab (default: {DEFAULT_MIN_REVIEWERS})")
    ap.add_argument("--max-assigned", type=int, default=DEFAULT_MAX_ASSIGNED,
                    help=f"candidates are reviewers with 0 or with 1..N assignments (default N: {DEFAULT_MAX_ASSIGNED})")
    args = ap.parse_args()

    input_dir = Path(args.input_dir)
    if not input_dir.is_dir():
        sys.exit(f"Input folder not found: {input_dir}")
    reviews_txt = Path(args.reviews_txt) if args.reviews_txt else newest(input_dir, "*review_list*.txt")
    subs_xlsx = Path(args.submissions) if args.submissions else newest(input_dir, "SIGCSE_TS_2027_*.xlsx", exclude="review_list")
    if not reviews_txt:
        sys.exit(f"No TXT list of reviews found in {input_dir} (*review_list*.txt)")
    assignment_dir = Path(args.assignment_dir) if args.assignment_dir else input_dir / "assignment"
    for name in ("assignment.csv", "reviewer.csv"):
        if not (assignment_dir / name).exists():
            sys.exit(f"Missing {assignment_dir / name} (Assignment -> Download in CSV)")
    out_name = f"review_stats_{datetime.now():%Y-%m-%d_%H%M}.xlsx"
    out = Path(args.output) if args.output else Path(args.output_dir) / out_name

    print(f"Reviews:      {reviews_txt.name}")
    print(f"Submissions:  {subs_xlsx.name if subs_xlsx else 'none (from assignments only)'}")
    print(f"Assignments:  {assignment_dir}")
    n_subs, n_reviews, n_assigned, n_short, warnings = build(
        reviews_txt, subs_xlsx, assignment_dir, out, args.min_reviewers, args.max_assigned
    )
    progress = f" ({n_reviews / n_assigned:.0%})" if n_assigned else ""
    print(f"\nSubmissions: {n_subs}, reviews submitted: {n_reviews} of {n_assigned}{progress}")
    print(f"Submissions with fewer than {args.min_reviewers} reviewers assigned: {n_short}")
    for w in warnings:
        print("WARNING:", w)
    print(f"\nDone: {out}")


if __name__ == "__main__":
    main()
